name: "setup_just"
description: "This GitHub Action will setup an environment with just."
author: "D.A.Pelasgus"
inputs:
  set-default:
    description: "Setup an environment with just"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Run just setup
      run: nix-shell just.nix
      shell: bash
branding:
  icon: "terminal"
  color: "purple"
